import-module activedirectory
#Body message
$body = "Dear Colleagues,
Please be informed that password for $user was changed
New password: $password 
Password and email were automatically generated by the script."


foreach ($user in $users = "user1", "user2" ){
    #Generating password
    $password =([System.Web.Security.Membership]::GeneratePassword(12,1))
    Set-ADAccountPassword -Identity $user -Reset -NewPassword (ConvertTo-SecureString -String $password -AsPlainText -Force) -server server.company.intranet
    Write-Host "For $user was setted passwofd:$password" -ForegroundColor Green -BackgroundColor Black
    #Sending email
    Send-MailMessage -From 'Sysadmins <chngpswd@company.com>' -To 'ba@company.com' -Cc 'audit.analysts@company.com' -Bcc 'mis@company.com' -Subject "New credential for $user" -Body $body -SmtpServer mail.company.com
    }
    